### PR TITLE
Dockerize backend 134

### LINKED ISSUE #134: Dockerise backend
We should dockerise the backend to make it easier for people, particularly our frontend developers, to get this running without needing to set things up (e.g. install the JDK, etc.). It should also start and run our PostgreSQL database.

Use a minimal Alpine distribution to run the Spring app.

For our development environment, we can use the preset Postgres credentials (username, password, host, etc.).

### PR DESCRIPTION
**Pull request by Wildschut**
## Summary of change

 Create Multistage Dockerfile to build maven project.
 Define booksapi service in docker-compose with required parameters.
 Create the container database dependency "checkpoint" shell. This script validates the passed environment variables or lack thereof.
Update the README.md to document the new required workflow with examples. 

## Related issue

Closes #134 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our Slack workspace or by creating a new [Q&A discussion on GitHub](https://github.com/Project-Books/books-api/discussions/categories/q-a)

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for working on this. Sure, feel free to revert them (e.g. using an interactive rebase). Let me know if you need a hand with this

**Comment by Wildschut** [comment]
Hi Karan, I think I've managed to revert the changes I made.

Can you please check if that is the case? 

Specifically the impact of these 4 commits:
image

If this fails (the git revert) I'll rather delete my fork and just redo the whole thing.

**Comment by knjk04** [comment]
@Wildschut Thanks a lot for this, I can see you've put a lot of thought into this!

I haven't been able to run this on Windows. Did you test this on Unix?

**Comment by Wildschut** [comment]
Hi @knjk04 , yes this was developed on an ubuntu machine.

I was heavily inspired by apache guacamole, so credit where credit is due...

That being said:
The OS shouldn't matter as long as the *.sh files have their line endings with LR and not CRLR. 

You should be able to verify if this is the case in intellij by opening the start.sh and looking in the bottom right (I think).

The dockerfile itself should be platform agnostic. And the build of the jar itself, the files get copied over to a linux container and compiled inside it, so thats abstracted away from the platform as well...

Otherwise, please share your output so I can help trace what is wrong/where its failing.

**Comment by Wildschut** [comment]
Hi @knjk04 , had you managed to get it running? 

Any feedback for me?

**Comment by knjk04** [comment]
Hi @Wildschut, I'm so sorry for the delay in getting back to you (frankly, I forgot). 

I'm using Docker Desktop on Windows (Docker Engine v20.10.8). I have buildkit enabled:

```json
  "features": {
    "buildkit": true
  }
```

I have also set it via Powershell using the answer from dev-null: https://stackoverflow.com/questions/62984255/docker-buildkit-for-docker-for-windows. 

Output of `docker-compose build booksapi`: https://gist.github.com/knjk04/15c4cba690ac74dfd522a4b77be33b8c. 

http://localhost:8080/graphiql: 

image

**Comment by Wildschut** [comment]
Hi @knjk04 , 

Thanks for getting back to me :D

Ok, so from the output you've shared the build is passing. So the booksapi image is being created. 

Now what remains is to run the image - create an container.

Can you please share the output of the following command `docker-compose up booksapi`. And please share the docker-compose.yml. I'd like to verify the env's your passing...

**Comment by knjk04** [comment]
```
PS C:\Users\karan\playground\bapi-docker-139> docker-compose up -d
Recreating booksapi ...
Recreating booksapi ... done
PS C:\Users\karan\playground\bapi-docker-139> docker logs -f booksapi
: No such file or directory
PS C:\Users\karan\playground\bapi-docker-139>
```

image

It looks like it's still not running. See [docker-compose](https://gist.github.com/knjk04/035feae0b78390399d72870189f3e452).

**Comment by Wildschut** [comment]
Ok, based off the error you've received (127), the start.sh file attributes (line endings) has been changed. 

Please execute the follow ps command: 
`Get-Content ./docker/bin/start.sh  
 -raw | % {$_ -replace "`r", ""} | Set-Content -NoNewline ./docker/bin/start.sh `

Then refresh the image by rebuilding it:
`docker-compose build --build-arg mvn_arg="clean package -DskipTests"`

Finally generate an container of the refreshed image:
`docker-compose up booksapi`

**Review by knjk04 — CHANGES_REQUESTED** [review]
@Wildschut Thanks a lot for this and for suggesting the line endings fix! It works great.

Could you please resolve the merge conflict and change the port the backend runs on from 8080 to 8082 (to avoid a conflict when run locally with the Books API)?

**Comment by knjk04** [comment]
@Wildschut Do you have an update on this?

**Comment by Wildschut** [comment]
Hi @knjk04 , was out of the loop for a while.

I'll resolve it within 3 days. Once done, I'll mention you so this van move forward.

Thanks

**Comment by knjk04** [comment]
@Wildschut I've made the necessary changes, as someone else's work depends on this. Thanks a lot for all of your help with this!

**Review by knjk04 — APPROVED** [review]

**Pull request merged**
