### PR TITLE
Add book in author schema 28

### LINKED ISSUE #28: Add book in author schema
`#    books: [Book!]! TODO: bring this back`

In the `Author` schema, uncomment the `books` line and get it to work. It should be possible to find all of the books that belong to a particular author

### PR DESCRIPTION
**Pull request by nikole24**
## Summary of change

You can find all books of a specific author.

## Related issue

Closes #28 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our Slack workspace or by creating a new [Q&A discussion on GitHub](https://github.com/Project-Books/books-api/discussions/categories/q-a)

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for working on this! Could you please resolve the conflict in query.graphqls?

**Comment by knjk04** [comment]
@nikole24 Does this work for you on `localhost:8080/playground`? It doesn't for me. I get back an empty list

**Comment by nikole24** [comment]
yes it works.
Screenshot (385)

**Comment by knjk04** [comment]
Oops, my bad. I was missing the dot after the 'K' in 'J.K.'

**Review by knjk04 — APPROVED** [review]
Thanks for working on this! I've made some small improvements

**Pull request merged**
