### PR TITLE
Making blurb field required

### LINKED ISSUE #14: Make the blurb field required
Make the `blurb` field required in the `Book` entity and schema

### PR DESCRIPTION
**Pull request by navneet35**
## Summary of change

Making the blurb field required.

## Related issue

Closes #14

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for working on this! Could you also please add the blurb field to the constructor?

**Comment by navneet35** [comment]
> 
> 
> Thanks for working on this! Could you also please add the blurb field to the constructor?

Please provide the values need to be added in the book instances created in [BooksApiApplication](https://github.com/Project-Books/books-api/blob/c83fdc70a2d5292b607280fac56692001d701819/src/main/java/com/karankumar/booksapi/BooksApiApplication.java#L44)

**Comment by knjk04** [comment]
You can put anything in, it's just test data

**Comment by navneet35** [comment]
> 
> 
> You can put anything in, it's just test data. Thanks

Added the blurb in the constructor args. Thanks!

**Review by knjk04 — APPROVED** [review]
Thanks for working on this!

**Pull request merged**
