### PR TITLE
Shivansh Added issue 11

### PR DESCRIPTION
**Pull request by shivansh29**
## Summary of change

[Please briefly describe what you have changed.]

## Related issue

Closes #[issue number]

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [ ] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

### CODE REVIEW

**Comment by knjk04** [comment]
Thanks for working on this. Could you please fill in the PR description (see a merged in PR if you need an example)?

**Comment by shivansh29** [comment]
could you give a link of a merged PR

**Comment by knjk04** [comment]
@shivansh29 Any of these: https://github.com/Project-Books/books-api/pulls?q=is%3Apr+is%3Amerged+

**Comment by knjk04** [comment]
I noticed that your source branch is `main`. Could you please create a new branch (`git branch -m <new-branch-name>`)? You'll need to create a PR as this one will be invalid.

If you need a hand with anything, feel free to reach out to us on our help channel on Slack

**Pull request closed without merging**
