### PR TITLE
Add series issue 6

### LINKED ISSUE #6: Add series
If a book is in a series, it should be possible to see:

1) Its position in the series
2) The name of the series (e.g. 'Harry Potter' for the Harry Potter books)
3) Other books in the same series

### PR DESCRIPTION
**Pull request by kev711**
## Summary of change

If a book is in a series, it should be possible to see:

Its position in the series
`com.karankumar.booksapi.repository.BookRepository.getBookPositionInBookSeries()`
The name of the series (e.g. 'Harry Potter' for the Harry Potter books)
`com.karankumar.booksapi.repository.BookRepository.getAllBookSeriesForBook()`
Other books in the same series
`com.karankumar.booksapi.repository.BookSeriesMappingRepository.getAllBooksByBookSeries()`

## Related issue

Closes #6

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [x] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [x] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [x] Ensure code changes pass all tests

- [x] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [x] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [x] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [x] Set this pull request to 'draft' if you are still working on it

- [x] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our Slack workspace or by creating a new [Q&A discussion on GitHub](https://github.com/Project-Books/books-api/discussions/categories/q-a)

### CODE REVIEW

**Comment by kev711** [comment]
@knjk04 Created a new one for this issue.

**Comment by knjk04** [comment]
Thanks for working on this. I'm still reviewing this

**Review by knjk04 — CHANGES_REQUESTED** [review]
image

Would it be possible to add book series to the schema so that we can access it in queries?

**Comment by knjk04** [comment]
@kev711 How are you getting on with this?

**Comment by kev711** [comment]
> @kev711 How are you getting on with this?

The flyway migration for `AUTHOR` is failing. Trying to resolve. Also, do I use `-dev` profile for starting the application ?

**Comment by knjk04** [comment]
> The flyway migration for AUTHOR is failing.

Could you send the output? It's fine on my end.

> Also, how do I use -dev profile for starting the application ?

What are you using the run the application (e.g. IntelliJ, Eclipse, terminal, etc.)?

**Comment by knjk04** [comment]
@kev711 Following up on this

**Comment by kev711** [comment]
Hi @knjk04 
Due to time commitments I won't be able to add to this work at this time. Thanks for working with me!

**Comment by knjk04** [comment]
@kev711 Thanks for letting us know

**Pull request closed without merging**
