### PR TITLE
Add optional about field to Author schema

### LINKED ISSUE #13: Add about field to Author
Add an 'about' field to the `Author` entity and schema. This should be optional

### PR DESCRIPTION
**Pull request by ofvoler**
## Summary of change

Add optional about field to Author entity (Author.java and author.graphqls).

## Related issue

Closes #13 

## Pull request checklist

Please keep this checklist in & ensure you have done the following:

- [X] Read, understood and adhered to our [contributing document](https://github.com/knjk04/book-project/blob/master/CONTRIBUTING.md).
  - [X] Ensure that you were first assigned to a relevant issue before creating this pull request
  - [X] Ensure code changes pass all tests

- [X] Read, understood and adhered to our [style guide](https://github.com/knjk04/book-project/blob/master/STYLEGUIDE.md). A lot of our code reviews are spent on ensuring compliance with our style guide, so it would save a lot of time if this was adhered to from the outset. 

- [X] Filled in the summary, context (if applicable) and related issue section. Replace the square brackets and its placeholder content with your contents. For an example, see any merged in pull request

- [X] Created a branch that has a descriptive name (what your branch is for in a few words and includes the issue number at the end, e.g. `test-reading-goal-123`

- [X] Set this pull request to 'draft' if you are still working on it

- [X] Resolved any merge conflicts

For any of the optional checkboxes (e.g. the screenshots one), still check it if it does not apply.

If in doubt, get in touch with us via our [Slack workspace](https://join.slack.com/t/teambookproject/shared_invite/zt-jcijyenp-JiKFGBv62FIPoFnvOW6Ubg)

### CODE REVIEW

**Comment by ofvoler** [comment]
I didn't add testing for this in BooksApiApplication.java, because blurb was the most similar field and that wasn't added either. I also didn't test it because it seemed like the other optional fields aren't being tested. Let me know if I need to implement either of those things!

**Review by knjk04 — CHANGES_REQUESTED** [review]
> I didn't add testing for this in BooksApiApplication.java, because blurb was the most similar field and that wasn't added either. I also didn't test it because it seemed like the other optional fields aren't being tested. Let me know if I need to implement either of those things!

That's fine, we can prepopulate later if needed. We don't need to test this right now as it is quite simple with just a getter and a setter.

It looks like you did the right thing in the wrong files. The `Book` schema already has a `blurb` field, but this issue was to add an `about` field to the `Author` schema (a brief description about an `Author`). Could you please change this?

**Comment by ofvoler** [comment]
Okay! I made the changes, squashed the commits, and rebased from main so my branch is up-to-date.

**Review by knjk04 — APPROVED** [review]
Thanks for making the changes!

**Pull request merged**
